import {useRef,type ReactNode} from 'react';import type {ApiError} from '../api/client';
const L:Record<string,[string,string]>={SUCCEEDED:['Succeeded','ok'],RUNNING_BASELINE:['Running baseline','run'],INJECTING:['Injecting','run'],OBSERVING:['Observing','run'],CLEANING_UP:['Cleaning up','run'],VERIFYING_RECOVERY:['Verifying recovery','run'],QUEUED:['Queued','mu'],VALIDATING:['Validating','run'],ABORTING:['Aborting','wn'],ABORTED:['Aborted','wn'],FAILED:['Failed','er'],PASSED:['Passed','ok'],FAILED_HYPOTHESIS:['Hypothesis failed','er'],PENDING:['Pending','mu'],NOT_STARTED:['Not started','mu'],NOT_REQUIRED:['Not required','mu'],ACTIVE:['Active','wn'],REMOVED:['Removed','ok'],REMOVAL_FAILED:['Removal failed','er'],UNVERIFIED:['Unverified','wn']};
export const Badge=({v,cleanup}:{v:string;cleanup?:boolean})=>{const [t,c]=v==='FAILED'&&cleanup?['Cleanup failed','er']:L[v]??[v,'mu'];return <span className={`b ${c}`}>{t}</span>};
export const Loading=()=><div className="card" role="status">Loading…</div>;
export const ErrorState=({e}:{e:unknown})=><div className="card warn" role="alert"><b>Something went wrong</b><p>{(e as ApiError)?.message??'Unknown error'}</p></div>;
export const Empty=({children}:{children:ReactNode})=><div className="card">{children}</div>;
export const Table=({head,rows}:{head:string[];rows:ReactNode[][]})=><div className="tw"><table><thead><tr>{head.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>;
export function Confirm({title,text,action,onYes,children}:{title:string;text:string;action:string;onYes:()=>void;children:string}){const d=useRef<HTMLDialogElement>(null);
 return <><button className="btn d" onClick={()=>d.current?.showModal()}>{children}</button><dialog ref={d} onClose={()=>d.current?.returnValue==='yes'&&onYes()}><form method="dialog"><h3>{title}</h3><p>{text}</p><button className="btn s" value="no">Cancel</button> <button className="btn d" value="yes">{action}</button></form></dialog></>}
