import {Link} from 'react-router-dom';import {Bar,BarChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {useActiveFaults,useEngines,useExperiments,useRuns} from '../api/hooks';import {Badge,ErrorState,Loading,Table} from '../components/ui';
export default function Dashboard(){const ex=useExperiments(),runs=useRuns('limit=100'),eng=useEngines(),f=useActiveFaults();
 if(runs.isLoading)return <Loading/>;if(runs.isError)return <ErrorState e={runs.error}/>;
 const r=runs.data!,n=(p:(x:typeof r[0])=>boolean)=>r.filter(p).length;
 const cards:[string,number|string,string][]=[['Total Experiments',ex.data?.length??'—','/experiments'],['Active Runs',n(x=>['QUEUED','VALIDATING','RUNNING_BASELINE','INJECTING','OBSERVING','ABORTING','CLEANING_UP','VERIFYING_RECOVERY'].includes(x.status)),'/runs/active'],['Successful Runs',n(x=>x.outcome==='PASSED'),'/runs'],['Failed Resilience Checks',n(x=>x.outcome==='FAILED_HYPOTHESIS'),'/runs'],['Active Faults',f.data?.length??'—','/faults'],['Cleanup Issues',n(x=>x.cleanup_status==='FAILED'),'/faults']];
 const chart=[['Passed',n(x=>x.outcome==='PASSED')],['Hypothesis failed',n(x=>x.outcome==='FAILED_HYPOTHESIS')],['Aborted',n(x=>x.status==='ABORTED')],['Execution failed',n(x=>x.status==='FAILED')],['Cleanup failed',n(x=>x.cleanup_status==='FAILED')]].map(([name,v])=>({name,v}));
 return <><h2>Chaos Engineering Overview</h2><p className="sub">Monitor experiments, failure injection, and recovery across your environments.</p>
 <p><Link className="btn" to="/experiments/new">Create Experiment</Link> <Link className="btn s" to="/runs/active">View Active Runs</Link></p><br/>
 <div className="grid">{cards.map(([l,v,to])=><Link key={l} to={to} className="card" style={{color:'inherit',textDecoration:'none'}}><div className="mu">{l}</div><div className="big">{v}</div></Link>)}</div>
 {!!f.data?.length&&<div className="card warn"><b>{f.data.length} active fault(s)</b> <Link to="/faults">Review</Link>. Nothing is cleaned up automatically.</div>}
 <div className="g2"><div className="card"><h3>Outcomes (last {r.length} runs)</h3><div style={{height:220}} role="img" aria-label={chart.map(c=>`${c.name} ${c.v}`).join(', ')}><ResponsiveContainer><BarChart data={chart}><XAxis dataKey="name" fontSize={11}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="v" fill="var(--ac)"/></BarChart></ResponsiveContainer></div></div>
 <div className="card"><h3>Engines</h3>{eng.isError?<ErrorState e={eng.error}/>:eng.data?.map(e=>{const isConfigured=e.configured??(e as any).enabled??false;const isReachable=e.reachable??(e as any).available??false;return <p key={e.name}><Link to={`/engines/${e.name}`}>{e.name}</Link> <span className={`b ${!isConfigured?'mu':isReachable?'ok':'er'}`}>{!isConfigured?'Not configured':isReachable?'Reachable':'Unreachable'}</span></p>})}</div></div>
 <div className="card"><h3>Recent runs</h3>{r.length?<Table head={['Experiment','Engine','Target','Started','Execution','Outcome','Cleanup','']} rows={r.slice(0,8).map(x=>[x.definition_snapshot.metadata.name,x.definition_snapshot.spec.fault.engine,x.definition_snapshot.spec.target.environment+':'+x.definition_snapshot.spec.target.service,x.started_at?new Date(x.started_at).toLocaleString():'Pending',<Badge v={x.status}/>,<Badge v={x.outcome}/>,<Badge v={x.cleanup_status} cleanup/>,<Link to={`/runs/${x.id}`}>View details</Link>])}/>:<p>No runs yet. Create an experiment to start.</p>}</div></>}
