import {NavLink,Route,Routes,useLocation} from 'react-router-dom';import {lazy,Suspense,useEffect,useState} from 'react';
import {useEngines} from './api/hooks';import {Loading} from './components/ui';
const Dashboard=lazy(()=>import('./pages/Dashboard')),Experiments=lazy(()=>import('./pages/Experiments')),NewExperiment=lazy(()=>import('./pages/NewExperiment')),Runs=lazy(()=>import('./pages/Runs')),RunDetail=lazy(()=>import('./pages/RunDetail')),Faults=lazy(()=>import('./pages/Faults')),Environments=lazy(()=>import('./pages/Environments')),EnginePage=lazy(()=>import('./pages/EnginePage')),Reports=lazy(()=>import('./pages/Reports')),Settings=lazy(()=>import('./pages/Settings')),Pipeline=lazy(()=>import('./pages/Pipeline'));
const NAV:[string,[string,string][]][]=[['Overview',[['/dashboard','Dashboard']]],['CI/CD Automation',[['/pipeline','CI/CD Pipeline']]],['Experiments',[['/experiments','All Experiments'],['/experiments/new','Create Experiment']]],['Operations',[['/runs/active','Active Runs'],['/faults','Active Faults'],['/environments','Environments']]],['Engines',[['/engines/chaos-toolkit','Chaos Toolkit'],['/engines/pumba','Pumba'],['/engines/toxiproxy','Toxiproxy'],['/engines/chaos-mesh','Chaos Mesh']]],['Insights',[['/runs','Run History'],['/reports','Reports']]],['Administration',[['/settings','Settings']]]];
export default function App(){const [theme,setTheme]=useState(localStorage.getItem('theme')??'dark');const {pathname}=useLocation();const eng=useEngines();
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);
 return <div className="app"><nav className="side" aria-label="Main"><h1>ChaosLab</h1>{NAV.map(([g,l])=><div key={g}><small>{g}</small>{l.map(([to,t])=><NavLink key={to} to={to} end>{t}</NavLink>)}</div>)}</nav>
 <div className="main"><header className="top"><b>{pathname.slice(1).replace(/\//g,' / ')||'dashboard'}</b><span className="sp"/>
 <span className={`b ${eng.isError?'er':eng.isSuccess?'ok':'mu'}`}>{eng.isError?'API unavailable':eng.isSuccess?'API connected':'Checking API'}</span>
 <button className="btn s" aria-label="Toggle theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>Theme</button></header>
 <div className="page"><Suspense fallback={<Loading/>}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/pipeline" element={<Pipeline/>}/><Route path="/experiments" element={<Experiments/>}/><Route path="/experiments/new" element={<NewExperiment/>}/><Route path="/runs" element={<Runs/>}/><Route path="/runs/active" element={<Runs active/>}/><Route path="/runs/:runId" element={<RunDetail/>}/><Route path="/faults" element={<Faults/>}/><Route path="/environments" element={<Environments/>}/><Route path="/engines/:name" element={<EnginePage/>}/><Route path="/reports" element={<Reports/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<h2>Page not found</h2>}/></Routes></Suspense></div></div></div>}
